FROM node:14 AS development

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install glob rimraf

RUN npm install

COPY ./dist/apps/db-data-seeder .

COPY ./files/numbers.csv .

CMD ["node", "main"]
